## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(bJ+uKlBjb/7HNa8NfimCE6Uf8HPQqsJF)
      client-secret: ENC(bJ+uKlBjb/7HNa8NfimCE6Uf8HPQqsJF)
      scope: server

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345a
    url: jdbc:mysql://localhost:3306/bingglew?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  resources:
    static-locations: classpath:/static/,classpath:/views/

# 直接放行URL
ignore:
  urls:
    - /actuator/**
